package prototipointerface;

import java.awt.Color;
import javax.swing.JPanel;

public class Janela extends javax.swing.JFrame {

    public Janela() {
        //configuração para poder dar efeito de clique e mouse passando por cima dos botões
        initComponents();
        abaBotao1.setVisible(false);
        botao1Select.setVisible(false);
        abaBotao2.setVisible(false);
        botao2Select.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        PainelBotoes = new javax.swing.JPanel();
        linhaHorizontalPainel = new javax.swing.JPanel();
        botao1 = new javax.swing.JPanel();
        textoBotao1 = new javax.swing.JLabel();
        abaBotao1 = new javax.swing.JPanel();
        botao1Select = new javax.swing.JPanel();
        textoBotao2 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        titulo5 = new javax.swing.JLabel();
        titulo6 = new javax.swing.JLabel();
        botao2 = new javax.swing.JPanel();
        textoBotao3 = new javax.swing.JLabel();
        abaBotao2 = new javax.swing.JPanel();
        botao2Select = new javax.swing.JPanel();
        textoBotao4 = new javax.swing.JLabel();
        painel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de Calculo");
        setLocation(new java.awt.Point(400, 120));
        setName("janelaPrincipal"); // NOI18N
        setResizable(false);

        painelFundo.setBackground(new java.awt.Color(255, 255, 255));
        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelBotoes.setBackground(new java.awt.Color(56, 55, 55));

        javax.swing.GroupLayout linhaHorizontalPainelLayout = new javax.swing.GroupLayout(linhaHorizontalPainel);
        linhaHorizontalPainel.setLayout(linhaHorizontalPainelLayout);
        linhaHorizontalPainelLayout.setHorizontalGroup(
            linhaHorizontalPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        linhaHorizontalPainelLayout.setVerticalGroup(
            linhaHorizontalPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        botao1.setBackground(new java.awt.Color(68, 68, 68));
        botao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao1MouseExited(evt);
            }
        });
        botao1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBotao1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        textoBotao1.setForeground(new java.awt.Color(204, 204, 204));
        textoBotao1.setText("Matriz X e Y (Coordenadas)");
        botao1.add(textoBotao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        abaBotao1.setBackground(new java.awt.Color(153, 153, 153));
        abaBotao1.setPreferredSize(new java.awt.Dimension(4, 76));
        abaBotao1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        botao1.add(abaBotao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 8, -1));

        botao1Select.setBackground(new java.awt.Color(102, 102, 102));
        botao1Select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao1SelectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao1SelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao1SelectMouseExited(evt);
            }
        });
        botao1Select.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBotao2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        textoBotao2.setForeground(new java.awt.Color(204, 204, 204));
        textoBotao2.setText("Matriz X e Y (Coordenadas)");
        botao1Select.add(textoBotao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        botao1.add(botao1Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 76));

        titulo1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(204, 204, 204));
        titulo1.setText("v1.02");

        titulo2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(204, 204, 204));
        titulo2.setText("Funções Matematicas ");

        titulo3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        titulo3.setForeground(new java.awt.Color(204, 204, 204));
        titulo3.setText("Calculos ");

        titulo5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titulo5.setForeground(new java.awt.Color(204, 204, 204));
        titulo5.setText("&");

        titulo6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titulo6.setForeground(new java.awt.Color(204, 204, 204));
        titulo6.setText("Geometria");

        botao2.setBackground(new java.awt.Color(68, 68, 68));
        botao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao2MouseExited(evt);
            }
        });
        botao2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBotao3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        textoBotao3.setForeground(new java.awt.Color(204, 204, 204));
        textoBotao3.setText("Triangulo");
        botao2.add(textoBotao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 25, -1, -1));

        abaBotao2.setBackground(new java.awt.Color(153, 153, 153));
        abaBotao2.setPreferredSize(new java.awt.Dimension(4, 76));
        abaBotao2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        botao2.add(abaBotao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 8, -1));

        botao2Select.setBackground(new java.awt.Color(102, 102, 102));
        botao2Select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao2SelectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao2SelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao2SelectMouseExited(evt);
            }
        });
        botao2Select.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBotao4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        textoBotao4.setForeground(new java.awt.Color(204, 204, 204));
        textoBotao4.setText("Triangulo");
        botao2Select.add(textoBotao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 25, -1, -1));

        botao2.add(botao2Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 76));

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo3)
                    .addGroup(PainelBotoesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelBotoesLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(titulo5)
                                .addGap(18, 18, 18)
                                .addComponent(titulo6)
                                .addGap(67, 67, 67))
                            .addComponent(titulo2)))
                    .addGroup(PainelBotoesLayout.createSequentialGroup()
                        .addComponent(linhaHorizontalPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo1)
                .addGap(52, 52, 52))
            .addComponent(botao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo6)
                    .addComponent(titulo5))
                .addGap(18, 18, 18)
                .addComponent(linhaHorizontalPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        painelFundo.add(PainelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 850));

        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelFundo.add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 0, 700, 850));

        getContentPane().add(painelFundo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseEntered
        setarCorBotao(botao1);


    }//GEN-LAST:event_botao1MouseEntered

    private void botao1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseExited
        // TODO add your handling code here:
        resetarCorBotao(botao1);
    }//GEN-LAST:event_botao1MouseExited

    private void botao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1MouseClicked

        abaBotao1.setVisible(true);
        setarCorBotao(botao1);
        botao1Select.setVisible(true);
        botao2Select.setVisible(false);
        abaBotao2.setVisible(false);

    }//GEN-LAST:event_botao1MouseClicked

    private void botao1SelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1SelectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botao1SelectMouseClicked

    private void botao1SelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1SelectMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botao1SelectMouseEntered

    private void botao1SelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao1SelectMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botao1SelectMouseExited

    private void botao2SelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2SelectMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botao2SelectMouseClicked

    private void botao2SelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2SelectMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botao2SelectMouseEntered

    private void botao2SelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2SelectMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botao2SelectMouseExited

    private void botao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseClicked
        // TODO add your handling code here:
         abaBotao2.setVisible(true);
        setarCorBotao(botao2);
        botao2Select.setVisible(true);
        botao1Select.setVisible(false);
        abaBotao1.setVisible(false);
    }//GEN-LAST:event_botao2MouseClicked

    private void botao2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseEntered
        // TODO add your handling code here
        setarCorBotao(botao2);


    }//GEN-LAST:event_botao2MouseEntered

    private void botao2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao2MouseExited
        // TODO add your handling code here:
        resetarCorBotao(botao2);
    }//GEN-LAST:event_botao2MouseExited

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    public void setarCorBotao(JPanel panel) {
        panel.setBackground(new Color(68, 68, 68));
    }

    public void resetarCorBotao(JPanel panel) {
        panel.setBackground(new Color(56, 55, 55));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel abaBotao1;
    private javax.swing.JPanel abaBotao2;
    private javax.swing.JPanel botao1;
    private javax.swing.JPanel botao1Select;
    private javax.swing.JPanel botao2;
    private javax.swing.JPanel botao2Select;
    private javax.swing.JPanel linhaHorizontalPainel;
    private javax.swing.JPanel painel1;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JLabel textoBotao1;
    private javax.swing.JLabel textoBotao2;
    private javax.swing.JLabel textoBotao3;
    private javax.swing.JLabel textoBotao4;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo5;
    private javax.swing.JLabel titulo6;
    // End of variables declaration//GEN-END:variables
}
